theme = "gleam"

[editor]
auto-pairs = false

[keys.insert]
# different for insert/normal
esc = "command_mode"
Meta-p = "command_mode"
C-A-p = "command_mode"
C-p = "command_mode"
A-p = "command_mode"

# same for all modes
Meta-r = [":config-reload", ":rl", ":lsp-restart"]
S-up = "search_prev"
S-down = "search_next"
S-left = "shrink_selection"
S-right = "expand_selection"

Meta-f = ["search_selection", "search", "commit_undo_checkpoint"]
C-A-f = ["search_selection", "search", "commit_undo_checkpoint"]
C-f = ["search_selection", "search", "commit_undo_checkpoint"]
A-f = ["search_selection", "search", "commit_undo_checkpoint"]

Meta-c = [":clipboard-yank-join", "yank"]
C-A-c = [":clipboard-yank-join", "yank"]
C-c = [":clipboard-yank-join", "yank"]
A-c = [":clipboard-yank-join", "yank"] 

Meta-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]
C-A-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]
C-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]
A-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]

# Meta-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]
C-A-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]
C-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]
A-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]

"Meta-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]
"C-A-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]
"C-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]
"A-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]

# Meta-down = "copy_selection_on_next_line"
C-A-down = "copy_selection_on_next_line"
# C-down = "copy_selection_on_next_line"
A-down = "copy_selection_on_next_line"

Meta-s = [":write", "commit_undo_checkpoint"]
C-A-s = [":write", "commit_undo_checkpoint"]
C-s = [":write", "commit_undo_checkpoint"]
A-s = [":write", "commit_undo_checkpoint"]

"Meta-/" = ["toggle_comments", "commit_undo_checkpoint"]
"C-A-/" = ["toggle_comments", "commit_undo_checkpoint"]
"C-/" = ["toggle_comments", "commit_undo_checkpoint"]
"A-/" = ["toggle_comments", "commit_undo_checkpoint"]

Meta-z = "undo"
C-A-z = "undo"
# C-z = "undo"
# A-z = "undo"

# Meta-S-z = "redo"
C-S-A-z = "redo"
C-S-z = "redo"
A-S-z = "redo"

# Meta-left = "move_prev_word_start"
C-A-left = "move_prev_word_start"
# C-left = "move_prev_word_start"
# A-left = "move_prev_word_start"

# Meta-right = ["move_next_word_end", "move_char_right"]
C-A-right = ["move_next_word_end", "move_char_right"]
# C-right = ["move_next_word_end", "move_char_right"]
# A-right = ["move_next_word_end", "move_char_right"]

# Meta-w = [":wa", ":qa"]
C-A-w = [":wa", ":qa"]
C-w = [":wa", ":qa"]
A-w = [":wa", ":qa"]

[keys.normal]
# different for insert/normal
esc = "insert_mode"
ret = "insert_mode"
space = "insert_mode"
del = "insert_mode"
tab = "insert_mode"

# same for all modes
Meta-r = [":config-reload", ":rl", ":lsp-restart"]
S-up = "search_prev"
S-down = "search_next"
S-left = "shrink_selection"
S-right = "expand_selection"

Meta-f = ["search_selection", "search", "commit_undo_checkpoint"]
C-A-f = ["search_selection", "search", "commit_undo_checkpoint"]
C-f = ["search_selection", "search", "commit_undo_checkpoint"]
A-f = ["search_selection", "search", "commit_undo_checkpoint"]

Meta-c = [":clipboard-yank-join", "yank"]
C-A-c = [":clipboard-yank-join", "yank"]
C-c = [":clipboard-yank-join", "yank"]
A-c = [":clipboard-yank-join", "yank"] 

Meta-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]
C-A-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]
C-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]
A-x = [":clipboard-yank", "delete_selection", "commit_undo_checkpoint"]

# Meta-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]
C-A-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]
C-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]
A-v = ["delete_selection_noyank", "paste_before", "commit_undo_checkpoint"]

"Meta-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]
"C-A-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]
"C-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]
"A-'" = ["delete_selection_noyank", "commit_undo_checkpoint"]

# Meta-down = "copy_selection_on_next_line"
C-A-down = "copy_selection_on_next_line"
# C-down = "copy_selection_on_next_line"
A-down = "copy_selection_on_next_line"

Meta-s = [":write", "commit_undo_checkpoint"]
C-A-s = [":write", "commit_undo_checkpoint"]
C-s = [":write", "commit_undo_checkpoint"]
A-s = [":write", "commit_undo_checkpoint"]

"Meta-/" = ["toggle_comments", "commit_undo_checkpoint"]
"C-A-/" = ["toggle_comments", "commit_undo_checkpoint"]
"C-/" = ["toggle_comments", "commit_undo_checkpoint"]
"A-/" = ["toggle_comments", "commit_undo_checkpoint"]

Meta-z = "undo"
C-A-z = "undo"
# C-z = "undo"
# A-z = "undo"

# Meta-S-z = "redo"
C-S-A-z = "redo"
C-S-z = "redo"
A-S-z = "redo"

# Meta-left = "move_prev_word_start"
C-A-left = "move_prev_word_start"
# C-left = "move_prev_word_start"
# A-left = "move_prev_word_start"

# Meta-right = ["move_next_word_end", "move_char_right"]
C-A-right = ["move_next_word_end", "move_char_right"]
# C-right = ["move_next_word_end", "move_char_right"]
# A-right = ["move_next_word_end", "move_char_right"]

# Meta-w = [":wa", ":qa"]
C-A-w = [":wa", ":qa"]
C-w = [":wa", ":qa"]
A-w = [":wa", ":qa"]
