theme = "gleam"

[keys.insert]
Cmd-p = "normal_mode"
C-A-p = "normal_mode"
C-p = "normal_mode"
A-p = "normal_mode"

Cmd-c = ":clipboard-yank"
C-A-c = ":clipboard-yank"
C-c = ":clipboard-yank"
A-c = ":clipboard-yank"

Cmd-v = ":clipboard-paste-after"
C-A-v = ":clipboard-paste-after"
C-v = ":clipboard-paste-after"
A-v = ":clipboard-paste-after"

Cmd-down = "copy_selection_on_next_line"
C-A-down = "copy_selection_on_next_line"
C-down = "copy_selection_on_next_line"
A-down = "copy_selection_on_next_line"

Cmd-s = ":write"
C-A-s = ":write"
C-s = ":write"
A-s = ":write"

"Cmd-/" = "toggle_comments"
"C-A-/" = "toggle_comments"
"C-/" = "toggle_comments"
"A-/" = "toggle_comments"

Cmd-z = "undo"
C-A-z = "undo"
C-z = "undo"
A-z = "undo"

Cmd-S-z = "redo"
C-S-A-z = "redo"
C-S-z = "redo"
A-S-z = "redo"

Cmd-left  = "goto_line_start" # diff
C-A-left  = "move_prev_word_start"
C-left  = "move_prev_word_start"
A-left  = "move_prev_word_start"

Cmd-right = "goto_line_end_newline" # diff
C-A-right = ["move_next_word_end", "move_char_right"]
C-right = ["move_next_word_end", "move_char_right"]
A-right = ["move_next_word_end", "move_char_right"]

Cmd-w = [":wq", ":q!"]
C-A-w = [":wq", ":q!"]
C-w = [":wq", ":q!"]
A-w = [":wq", ":q!"]


[keys.normal]
esc = "insert_mode"

Cmd-c = ":clipboard-yank"
C-A-c = ":clipboard-yank"
C-c = ":clipboard-yank"
A-c = ":clipboard-yank"

Cmd-v = ":clipboard-paste-after"
C-A-v = ":clipboard-paste-after"
C-v = ":clipboard-paste-after"
A-v = ":clipboard-paste-after"

Cmd-down = "copy_selection_on_next_line"
C-A-down = "copy_selection_on_next_line"
C-down = "copy_selection_on_next_line"
A-down = "copy_selection_on_next_line"

Cmd-s = ":write"
C-A-s = ":write"
C-s = ":write"
A-s = ":write"

"Cmd-/" = "toggle_comments"
"C-A-/" = "toggle_comments"
"C-/" = "toggle_comments"
"A-/" = "toggle_comments"

Cmd-z = "undo"
C-A-z = "undo"
C-z = "undo"
A-z = "undo"

Cmd-S-z = "redo"
C-S-A-z = "redo"
C-S-z = "redo"
A-S-z = "redo"

Cmd-left  = "goto_line_start" # diff
C-A-left  = "move_prev_word_start"
C-left  = "move_prev_word_start"
A-left  = "move_prev_word_start"

Cmd-right = "goto_line_end_newline" # diff
C-A-right = ["move_next_word_end", "move_char_right"]
C-right = ["move_next_word_end", "move_char_right"]
A-right = ["move_next_word_end", "move_char_right"]

Cmd-w = [":wq", ":q!"]
C-A-w = [":wq", ":q!"]
C-w = [":wq", ":q!"]
A-w = [":wq", ":q!"]


[editor]
auto-pairs = false
