theme = "gleam"

[keys.insert]
Cmd-c = ":clipboard-yank"
Cmd-v = ":clipboard-paste-after"
C-A-down = "copy_selection_on_next_line"
Cmd-s = ":write"
"A-/" = "toggle_comments"
Cmd-z = "undo"
C-A-left  = "move_prev_word_start"
C-A-right = ["move_next_word_end", "move_char_right"]
A-w = ":wq"
C-w = ":wq"


[keys.normal]
Cmd-c = ":clipboard-yank"
Cmd-v = ":clipboard-paste-after"
C-s = ":write"
Cmd-s = ":write"
"C-," = ":open ~/.config/helix/config.toml"
"Cmd-/" = "toggle_comments"
A-w = ":wq"
C-w = ":wq"

[editor]
auto-pairs = false
